export { default as Welcome } from './Welcome/Welcome'
export { default as Auth } from './Auth/Auth'
export { default as Home } from './Home/Home'
export { default as Search } from './Search/Search'
export { default as CreatePost } from './CreatePost/CreatePost'
export { default as Profile } from './Profile/Profile'
